---
  - name: Clone Homestead
    git:
      repo: "{{ homestead_repo }}"
      dest: "{{ homestead_dir }}"
      version: "{{ homestead_release }}"

  - name: Init Homestead
    shell: bash "{{ homestead_dir }}/init.sh"

  - name: Create Homestead.yaml
    template:
      src: files/Homestead.yaml.j2
      dest: "{{ homestead_dir }}/Homestead.yaml"
