---
  - name: Clone Homestead
    git:
      repo: "{{ homestead-repo }}"
      dest: "{{ homestead-dir }}"
      version: "{{ homestead-release }}"

  - name: Init Homestead
    shell: bash "{{ homestead-dir }}/init.sh"

  - name: Create Homestead.yaml
    template:
      src: files/Homestead.yaml.j2
      dest: "{{ homestead-dir }}/Homestead.yaml"
